app = "mango-geyser-services"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "us-docker.pkg.dev/mango-markets/gcr.io/mango-geyser-services:latest"

[processes]
  fills = "service-mango-fills fills-config.toml"
  pnl = "service-mango-pnl pnl-config.toml"

[[services]]
  processes = ["fills"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = "8080"

  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 1024

[[services]]
  processes = ["fills"]
  internal_port = 9091
  protocol = "tcp"

  [[services.ports]]
    port = "9091"

  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 1024

[[services]]
  processes = ["pnl"]
  internal_port = 2052
  protocol = "tcp"

  [[services.ports]]
    port = "2052"

  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 1024

[metrics]
  port = 9091
  path = "/metrics"
