bind_ws_addr = "0.0.0.0:8080"
rpc_http_url = "http://mango.rpcpool.com/30f906b6aab18aa6e59ec5eb421f"
mango_group = "78b8f4cGCwmZ9ysPFMWLaLTkkaYnUjwMJYStWe5RTSSX"

[metrics]
output_stdout = true
output_http = true

[source]
dedup_queue_size = 50000
rpc_ws_url = "wss://mango.rpcpool.com/30f906b6aab18aa6e59ec5eb421f"

[[source.grpc_sources]]
name = "accountsdb-client"
connection_string = "http://mango.rpcpool.com/30f906b6aab18aa6e59ec5eb421f"
retry_connection_sleep_secs = 30

[source.snapshot]
rpc_http_url = "http://mango.rpcpool.com/30f906b6aab18aa6e59ec5eb421f"
program_id = "4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg"
