[package]
name = "mango-feeds-connector"
version = "0.1.1"
authors = ["Christian Kamm <mail@ckamm.de>"]
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Listen to Solana account updates via geyser or websockets"

[lib]

[features]
default = ["solana-1-16"]
solana-1-14 = []
# v1.15.x got yanked
#solana-1-15 = ["rpc-account-scan-migrated"]
solana-1-16 = ["rpc-account-scan-migrated"]
rpc-account-scan-migrated = []

[dependencies]
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }

solana-rpc = { workspace = true }
solana-client = { workspace = true }
solana-account-decoder = { workspace = true }
solana-sdk = { workspace = true }
solana-logger = { workspace = true }

tokio = { workspace = true }
rustls = { workspace = true }

serde = { workspace = true }
serde_derive = { workspace = true }

log = { workspace = true }
anyhow = { workspace = true }

itertools = "0.10.5"

futures = { workspace = true }

async-channel = { workspace = true }
async-trait = { workspace = true }

warp = "0.3"

yellowstone-grpc-client = "1.9.0+solana.1.16.1"
yellowstone-grpc-proto = "1.9.0+solana.1.16.1"

[dev-dependencies]
clap = { version = "3.1.8", features = ["derive", "env"] }
