[package]
name = "mango-feeds-connector"
version = "0.1.1"
authors = ["Christian Kamm <mail@ckamm.de>"]
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Listen to Solana account updates via geyser or websockets"

[lib]

[features]
default = ["solana-1-14"]
solana-1-14 = []
solana-1-15 = []

[dependencies]
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ws", "http"] }

solana-rpc = "1.14.9"
solana-client = "1.14.9"
solana-account-decoder = "1.14.9"
solana-sdk = "1.14.9"

tokio = { version = "1", features = ["full"] }
rustls = "0.20.8"

serde = "1.0.130"
serde_derive = "1.0.130"

log = "0.4"
anyhow = "1.0"

itertools = "0.10.5"

futures = "0.3.17"

async-channel = "1.6"
async-trait = "0.1"

warp = "0.3"

yellowstone-grpc-proto = "1.1.0"

[dev-dependencies]
solana-logger = "*"
